// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzLz-onKzm-xkAXzd_OW5GpEl1hPYKHJs',
    appId: '1:688165818455:web:e47c6adbb9e4acf0ccd312',
    messagingSenderId: '688165818455',
    projectId: 'demo1-5bad3',
    authDomain: 'demo1-5bad3.firebaseapp.com',
    storageBucket: 'demo1-5bad3.firebasestorage.app',
    measurementId: 'G-S50BTN0MYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYgC1zOfc1yQ4rcXemDrj2xLOmz_ki1uw',
    appId: '1:688165818455:android:651434cc9ef449d6ccd312',
    messagingSenderId: '688165818455',
    projectId: 'demo1-5bad3',
    storageBucket: 'demo1-5bad3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO1BdVsDNmeBn86bYyWqKAILEwdzuYgAg',
    appId: '1:688165818455:ios:026d04bbb97cd7fbccd312',
    messagingSenderId: '688165818455',
    projectId: 'demo1-5bad3',
    storageBucket: 'demo1-5bad3.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO1BdVsDNmeBn86bYyWqKAILEwdzuYgAg',
    appId: '1:688165818455:ios:026d04bbb97cd7fbccd312',
    messagingSenderId: '688165818455',
    projectId: 'demo1-5bad3',
    storageBucket: 'demo1-5bad3.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzLz-onKzm-xkAXzd_OW5GpEl1hPYKHJs',
    appId: '1:688165818455:web:48dcc66f5e132bbcccd312',
    messagingSenderId: '688165818455',
    projectId: 'demo1-5bad3',
    authDomain: 'demo1-5bad3.firebaseapp.com',
    storageBucket: 'demo1-5bad3.firebasestorage.app',
    measurementId: 'G-0876Q5TCHG',
  );

}